### ISSUE TITLE
conversion slow with bundled ffmpeg binary

### ISSUE THREAD

**Issue by mh4ck** [eugeneware/ffmpeg-static#55] opened 2020-08-04 18:45 UTC
Why is running ffmpeg from this package is more than double so slow than running the command directly on the Machine?

I can't find any solution for this.

If i run the following code it takes 35s to convert a 13min webm video to mp3.
If i run the command logged in the "start" event directly on my machine it takes only 14s

```const fs = require("fs");
const moment = require("moment");
const ffmpegStatic = require("ffmpeg-static");
const ffmpeg = require("fluent-ffmpeg");
ffmpeg.setFfmpegPath(ffmpegStatic);

let outfile = fs.createWriteStream("music.mp3");
let infile = fs.createReadStream("video");

let startTime = moment().unix();
ffmpeg()
    .input(infile)
    .outputOptions([
        "-f mp3",
        "-vn",
        "-b:a 192k",
    ])
    .on('start', (commandLine) => {
      console.log(commandLine);
    })
    .on('error', (err, stdout, stderr) => {
        console.log(err);
    })
    .on('progress', (info) => {
        //console.log(info);
    })
    .on("end", () => {
        let endTime = moment().unix();
        console.log("Finished after " + (endTime - startTime) + "s");
    })
    .pipe(outfile);
```

**Comment by derhuerst** [comment] 2020-08-04 19:42
> If i run the command logged in the "start" event directly on my machine it takes only 14s

How do you run it? Using the same `ffmpeg` binary? With the same arguments?

**Comment by derhuerst** [comment] 2020-08-04 19:43
I'm just *guessing* here, but it might be slower because, in the Node.js process, you're reading the input file from disk and writing it to its stdout; Then, you let the ffmpeg process read it from `stdin`. Same with the output file, just flipped. This setup *might* have bottlenecks:
    - ffmpeg won't be able to seek the input file. This *may* be necessary to the job in a more efficient way.
    - The data has to be passed around (even copied?) several times. This *may* lead to a significant overhead with large files.

**Comment by mh4ck** [comment] 2020-08-04 19:49
Hi thank you for your answer. 

The first no i haven't used the ffmpeg binary located in the node modules i used the local installed version. 

I tried now the ffmpeg-static binary without nodejs and got the same result like with nodejs. It takes 35s.

So then is the question, why is the ffmpeg static library so slow? What is the difference and how can i speed it up?

**Comment by derhuerst** [comment] 2020-08-04 20:30
> So then is the question, why is the ffmpeg static library so slow? > What is the difference and how can i speed it up?

Not sure. All `ffmpeg-static` does is download a [pre-built binary](https://github.com/eugeneware/ffmpeg-static).

Before reporting this to the respective person publishing the binaries, please double-check your setup, make sure you‘re comparing the same ffmpeg versions, running in the same environment (e.g. no Docker, WSL, etc). Also, try running ffmpeg in verbose mode to find out if it uses hardware acceleration or not.

Once you‘ve confirmed a performance difference, report it with all details about your setup: OS & its version, ffmpeg version, flags used, CPUs & GPUs in your system etc.

**Comment by derhuerst** [comment] 2020-08-29 17:58
I'm going to close this Issue, because it seems that I cannot fix it here in `ffmpeg-static`.

**Closed by derhuerst** 2020-08-29 17:58 UTC
Labels: question
