### ISSUE TITLE
Support for Apple M1 Silicon?

### ISSUE THREAD

**Issue by sulaysumaria** [eugeneware/ffmpeg-static#83] opened 2021-05-26 06:05 UTC
Installing on Apple M1 fails with error `ffmpeg-static install failed: No binary found for architecture`.

Not sure if it is not supported yet but anyone has idea about this?

Node - v14.17.0
NPM - 7.14.0

**Comment by sulaysumaria** [comment] 2021-05-26 06:15
I just noticed the platform support is already added in master branch but the binaries are not yet available.

@eugeneware , any release date planned for updating the binaries and a new version on npm?

**Comment by eugeneware** [comment] 2021-05-26 06:22
@derhuerst Are the M1 binary version still a WIP or OK to be published to npm?

**Comment by derhuerst** [comment] 2021-05-26 10:08
The 4.4 binaries could be published, but I'm waiting for someone to provide a win32 binary, see #78.

**Comment by sulaysumaria** [comment] 2021-05-26 15:51
I just realised that it works fine on node `14.16.0` but install fails on `14.17.0`.

For anyone waiting for this release, you can downgrade to `14.16.0` for now and it works perfectly fine.

**Comment by louy2** [comment] 2021-06-02 21:46
Before the fix is published, is there a workaround not bound to a specific node version? I am on a locked version and met this problem.

**Comment by derhuerst** [comment] 2021-06-06 15:08
I don't think it's related to any version, I wouldn't know how that could be the case. If there *is* a issue, please post steps to reproduce it, e.g. logs.

Currently, no `ffmpeg-static` version has native support for Apple Silicon. You should be able to install the Intel x64 binary by installing with `export npm_config_arch=x64`.

**Comment by sulaysumaria** [comment] 2021-06-06 15:51
My node installation is using `nvm`. Maybe it is failing to set that environment variable. Not sure though, I will confirm and post here.

**Comment by derhuerst** [comment] 2021-06-07 11:36
>>You should be able to install the Intel x64 binary by installing with `export npm_config_arch=x64`.
>
> Maybe it is failing to set that environment variable.

You'll have to manually override that environment variable for now, because `ffmpeg-static` doesn't have native Apple Silicon binaries yet.

By default, npm should pass that variable to install scripts, but it contains the CPU architecture of your computer, which I assume is *not* `x64` (but `arm64`) if you run on Apple Silicon.

**Comment by codetheweb** [comment] 2021-06-19 23:40
Is this closed by the release of 4.4?

**Comment by derhuerst** [comment] 2021-06-22 14:02
Yes, this should be fixed with the `4.4` release.

Please let me know if it doesn't work.

**Closed by derhuerst** 2021-06-22 14:02 UTC
